[colors.cursor]
cursor = "#ffffb6"

[colors.hints.end]
background = "#ffffb6"
foreground = "#000000"

[colors.hints.start]
background = "#ffffb6"
foreground = "#000000"

[colors.line_indicator]
background = "#ffffb6"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "#ffffb6"

[cursor]
blink_interval = 800
thickness = 0.2
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "FiraMono Nerd Font"
# family = "Source Code Pro"
# family = "0xProto Nerd Font"

[font.offset]
x = 0
y = -1

[hints]
alphabet = "jfkdls;ahgurieowpqytmv,c.x/znb"

[[hints.enabled]]
command = "wl-copy"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Control"

[[keyboard.bindings]]
chars = "yank-buffer | fzf-word \r"
key = "B"
mods = "Control"

[[keyboard.bindings]]
chars = "yank-buffer all | fzf-word \r"
key = "B"
mods = "Shift|Control"

[[keyboard.bindings]]
chars = "alacritty msg config font.size=20\r"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "alacritty msg config font.size=11\r"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[window]
opacity = 0.8

[window.padding]
x = 0
y = 0
