#! /usr/bin/env sh

###                  _
###   ___ _   _  ___| | ___
###  / __| | | |/ __| |/ _ \
### | (__| |_| | (__| |  __/
###  \___|\__, |\___|_|\___|
###       |___/
###
### # # # # # #
###      #
### # # # # # #
###

: '
cycle
cycle swaybar i3blocks
copyright (c) 2023 - 2024  |  oxo

GNU GPLv3 GENERAL PUBLIC LICENSE
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
https://www.gnu.org/licenses/gpl-3.0.txt

@oxo@qoto.org


# dependencies
  n/a

# usage
  n/a

# examples
  n/a

# '


blocks_show_dir="$XDG_CONFIG_HOME/i3blocks/show"

cd $blocks_show_dir

## read lines (branche names) into array
readarray -t statuses < <(git branch | sed 's/^*//' | tr -d '[:blank:]\t')

current_status="$(git branch --show-current)"


# get current_status index from array

array_length=${#statuses[@]}

#for i in $array_lenght; do
for (( i=0; i<$array_length; i++ )); do

    printf "${statuses[$i]} $current_status\n"

    if [[ "${statuses[$i]}" = "${current_status}" ]]; then

	current_status_index="$i";
	# stop for loop on hit
	break

    fi

done


# next status index
number_of_statusses=$(( array_length - 1 ))
if [[ "$current_status_index" -lt "$number_of_statusses" ]]; then

    ((current_status_index++))
    next_status_index=$current_status_index

else

    next_status_index=0

fi

next_status="${statuses[$next_status_index]}"

git switch $next_status

cd -

sway reload

notify-send "$next_status"
