#! /usr/bin/env sh

# cycle swaybar i3blocks

blocks_show_dir="$XDG_CONFIG_HOME/i3blocks/show"

cd $blocks_show_dir

## read lines (branche names) into array
readarray -t statuses < <(git branch | sed 's/^*//' | tr -d '[:blank:]\t')

current_status="$(git branch --show-current)"


# get current_status index from array

array_length=${#statuses[@]}

#for i in $array_lenght; do
for (( i=0; i<$array_length; i++ )); do

    printf "${statuses[$i]} $current_status\n"

    if [[ "${statuses[$i]}" = "${current_status}" ]]; then

	current_status_index="$i";
	# stop for loop on hit
	break

    fi

done


# next status index
number_of_statusses=$(( array_length - 1 ))
if [[ "$current_status_index" -lt "$number_of_statusses" ]]; then

    ((current_status_index++))
    next_status_index=$current_status_index

else

    next_status_index=0

fi

next_status="${statuses[$next_status_index]}"

git switch $next_status

cd -

sway reload

notify-send "$next_status"
