#!/usr/bin/env sh

# toggle i3block groups


initialize() {

    # initialize
    ## code bar blocks dir
    code_bar_blocks="$XDG_CONFIG_HOME/code/bar_blocks"

    ## blocks current status
    current_status=$(cat "$XDG_CONFIG_HOME/code/bar_blocks/current_status")

    ## blocks show dir
    show_dir="$code_bar_blocks/show"

    ## blocks hide dir
    hide_dir="$code_bar_blocks/hide"

    ## network blocks
    network_blocks="wifi ipex macex interface macin ipin vrx vtx"

    #TODO
    ## weather_block
    weather_block='weather'

    ## core blocks
    core_blocks="temp cpu mem bt vol brightness batt"

    ## time
    # always on
}


identify_status() {

    # identify current blocks status
    ## status (0=off 1=on)

    ## define identifiers
    ## network
    vtx_in_show="$show_dir/vtx"
    ## core
    batt_in_show="$show_dir/batt"

    ## initial status
    ## network
    [[ -f $vtx_in_show ]] && network=1 || network=0
    ## core
    [[ -f $batt_in_show ]] && core=1 || core=0
}


cycle_blocks() {

    # identify block cycle
    ## cycle0 network0 core0
    ## cycle1 network0 core1
    ## cycle2 network1 core1
    case $network in

	0)
	    case $core in

		0)
		    cycle=0
		    ;;

		1)
		    cycle=1
		    ;;

	    esac
	    ;;

	1)
	    case $core in

		0)
		    cycle='n/a'
		    ;;

		1)
		    cycle=2
		    ;;

	    esac
	    ;;

    esac
}


define_action() {

    # define toggle action
    case $cycle in

	0)
	    # core show
	    for block in $core_blocks; do

		mv $hide_dir/$block $show_dir/$block

	    done
	    ;;

	1)
	    # network show
	    for block in $network_blocks; do

		mv $hide_dir/$block $show_dir/$block

	    done
	    ;;

	2)
	    # core and network hide
	    for block in $network_blocks; do

		mv $show_dir/$block $hide_dir/$block

	    done

	    for block in $core_blocks; do

		mv $show_dir/$block $hide_dir/$block

	    done
	    ;;

    esac
}


main() {
    initialize
    identify_status
    cycle_blocks
    define_action
}

main
