#! /usr/bin/env sh


csc="$XDG_CONFIG_HOME/sway/code"


# sourcing general scripts
source "$csc/get-parameters"
source "$csc/con-type-toggle"


vertical_fill()
{
    ## container height = monitor height
    ## container width = 1/divisor of monitor width
    divisor=4

    ## initially snap to east monitor border
    ## change position manually at will afterwards
    direction='E'

    set_width=$(echo "scale=0; $monitor_width"/"$divisor" | bc)
    #set_height=$(echo "scale=0; $monitor_height"/"$divisor" | bc)

    swaymsg "resize set width $set_width px height $monitor_height px"
    sh $csc/snap-move-to $direction
}


inform ()
{
    notify-send "${0##*/} $container_type $direction"
}


main()
{
    container_type_toggle
    vertical_fill
    inform
}

main
