#! /usr/bin/env sh

## toggle container type and minimize it's size

## height and width when minimized (px)
container_min_height=20
container_min_width=20


csc="$XDG_CONFIG_HOME/sway/code"


# get container data
source "$csc/get-focus-data"


minimize ()
{
    swaymsg "resize set width $container_min_width px height $container_min_height px"
}


container_type_toggle ()
{
    case $container_type in

	con)
	    swaymsg "floating enable"
	    notify-send "<>= minimized"
	    ;;

	floating_con)
	    swaymsg "floating disable"
	    notify-send "[]= minimized"
	    ;;

    esac
}


main ()
{
    container_type_toggle
    minimize
}

main
