#! /usr/bin/env sh


csc="$XDG_CONFIG_HOME/sway/code"


set_params()
{
    monitor_dimensions=$(
	swaymsg -t get_workspaces |
	    jq -r '.. | select(.focused?) |
	    select(.type=="workspace") |
	    .rect |
	    "\(.width)x\(.height)"' \
		      )

    monitor_width=${monitor_dimensions%x*}
    monitor_height=${monitor_dimensions#*x}

    selection=".focused?"

    mapfile -t container_params_arr < <( \
	swaymsg -t get_tree | \
	    jq -r ".. |
	    select(.type?) |
	    select($selection) |
	    .rect.x, .rect.y,
	    .rect.width, .rect.height,
	    .deco_rect.height, .type" \
		)

    container_curr_position=($(
	swaymsg -t get_tree |
	    jq -r '.. | select(.type?) |
	    select($selection) |
	    .rect |
	    "\(.x) \(.y)"' \
		      ))

    new_x=${container_params_arr[0]}
    new_y=${container_params_arr[1]}
    container_width=${container_params_arr[2]}
    container_height=${container_params_arr[3]}
    decor_height=${container_params_arr[4]}
    container_type=${container_params_arr[5]}
}


vertical_fill()
{
    ## container height = monitor height
    ## container width = 1/divisor of monitor width
    divisor=4

    ## initially snap to east monitor border
    ## change position manually at will afterwards
    direction='E'

    set_width=$(echo "scale=0; $monitor_width"/"$divisor" | bc)
    #set_height=$(echo "scale=0; $monitor_height"/"$divisor" | bc)

    swaymsg "resize set width $set_width px height $monitor_height px"
    sh $csc/snap-move-to $direction
}


container_type_toggle ()
{
    case $container_type in

	con)
	    swaymsg "floating enable"
	    container_type='floating_con'
	    ;;

	floating_con)
	    swaymsg "floating disable"
	    container_type='con'
	    ;;

    esac
}


inform ()
{
    notify-send "${0##*/} $container_type $direction"
}


main()
{
    set_params
    container_type_toggle
    vertical_fill
    inform
}

main
