#! /usr/bin/env sh

## toggle container type and minimize it's size

## height and width when minimized (px)
min_height=20
min_width=20


csc="$XDG_CONFIG_HOME/sway/code"


# get container data
source "$csc/get-parameters"


minimize ()
{
    swaymsg "resize set width $min_width px height $min_height px"
}


container_type_toggle ()
{
    case $container_type in

	con)
	    swaymsg "floating enable"
	    notify-send "float minimized"
	    ;;

	floating_con)
	    swaymsg "floating disable"
	    notify-send "tile minimized"
	    ;;

    esac
}


main ()
{
    get_parameters
    container_type_toggle
    minimize
}

main
