#! /usr/bin/env sh

## toggle container type and maximize it's size


csc="$XDG_CONFIG_HOME/sway/code"


# sourcing general scripts
source "$csc/get-focus-data"
source "$csc/con-type-toggle"


maximize ()
{
    ## height and width when minimized (px)
    max_width=$monitor_width
    max_height=$monitor_height

    swaymsg "resize set width $max_width px height $max_height px"
}


container_type_toggle ()
{
    case $container_type in

	con)
	    swaymsg "floating enable"
	    notify-send "float maximized"
	    ;;

	floating_con)
	    swaymsg "floating disable"
	    notify-send "tile maximized"
	    ;;

    esac
}


main ()
{
    container_type_toggle
    maximize
}

main
