#! /usr/bin/env sh


csc="$XDG_CONFIG_HOME/sway/code"


# sourcing general scripts
source "$csc/get-parameters"
source "$csc/con-type-toggle"


horizontal_fill()
{
    ## container width = monitor width
    ## container height = 1/divisor of monitor height
    divisor=4

    ## initially snap to south monitor border
    ## change position manually at will afterwards
    direction='N'

    #set_width=$(echo "scale=0; $monitor_width"/"$divisor" | bc)
    set_height=$(echo "scale=0; $monitor_height"/"$divisor" | bc)

    swaymsg "resize set width $monitor_width px height $set_height px"
    sh $csc/snap-move-to $direction
}


inform ()
{
    notify-send "${0##*/} $container_type $direction"
}


main()
{
    get_parameters
    container_type_toggle
    horizontal_fill
    inform
}

main
