#! /usr/bin/env sh

## toggle container type and set it's width in hexaparts

set_parameters()
{
    monitor_dimensions=$(
	swaymsg -t get_workspaces |
	    jq -r '.. | select(.focused?) |
	    select(.type=="workspace") |
	    .rect |
	    "\(.width)x\(.height)"' \
		      )

    monitor_width=${monitor_dimensions%x*}
    monitor_height=${monitor_dimensions#*x}

    selection=".focused?"
    #criteria=
    #[[ "$id" ]] && \
    #	{
    #	    selection=".id == $id"
    #	    criteria="[con_id = $id]"
    #	}

    mapfile -t container_params_arr < <( \
	swaymsg -t get_tree | \
	    jq -r ".. |
	    select(.type?) |
	    select($selection) |
	    .rect.x, .rect.y,
	    .rect.width, .rect.height,
	    .deco_rect.height, .type" \
		)

    new_x=${container_params_arr[0]}
    new_y=${container_params_arr[1]}
    container_width=${container_params_arr[2]}
    container_height=${container_params_arr[3]}
    decor_height=${container_params_arr[4]}
    container_type=${container_params_arr[5]}
}


minimize()
{
    swaymsg "resize set width 20 px height 20 px"
}


container_type_toggle ()
{
    case $container_type in

	con)
	    swaymsg "floating enable"
	    notify-send "float minimized"
	    ;;

	floating_con)
	    swaymsg "floating disable"
	    notify-send "tile minimized"
	    ;;

    esac
}


main()
{
    set_parameters
    container_type_toggle
    minimize
}

main
