#! /usr/bin/env sh

## toggle container type and set it's width in hexaparts

hexapart=$1


csc="$XDG_CONFIG_HOME/sway/code"


# get container data
source "$csc/get-parameters"


container_resize()
{
    case $hexapart in

	# 1/6, 1/3, 1/2, 2/3, 5/6 and full width
	## NOTICE $mod+Mod1+9 (maximize) also enables full width
	1|2|3|4|5|6)
	    counter=$hexapart
	    divisor=6
	    ;;

    esac

    set_width=$(echo "scale=0; $monitor_width*$counter/$divisor" | bc)
    set_height=$(echo "scale=0; $monitor_height*$counter/$divisor" | bc)

    swaymsg "resize set width $set_width px height $set_height px"
    #swaymsg "${criteria}resize set width $set_width px height $set_height px"
}


container_type_toggle ()
{
    case $container_type in

	con)
	    swaymsg "floating enable"
	    notify-send "float ${hexapart}/6"
	    ;;

	floating_con)
	    swaymsg "floating disable"
	    notify-send "tile ${hexapart}/6"
	    ;;

    esac
}


main()
{
    get_parameters
    container_type_toggle
    container_resize
}

main
