#! /usr/bin/env sh
#
##
### dimr
###	creates options for swaylock
###
### (c) 2019 - 2023  |  oxo
###
### usage:
###
###	% dimr swaylock_enable
###	enables swaylock timer to lock system after 2 * idle_time
###
###	% dimr swaylock_disable
###	disables swaylock timer function
###
###	% dimr screen_off [idle_time]
###	immediate screen_off
###
###	% dimr swaylock [idle_time]
###	initiate swaylock
##
#

[[ "$SWAYSOCK" ]] &&
{
    csc="$XDG_CONFIG_HOME/sway/code"
    dimr="$csc/dimr"
    lock="$csc/lock"

    option=$1
    idle_time=$2
    [[ -z $idle_time ]] && idle_time=120


    swaylock_status()
    {
	## status: ''/(no_)/swaylock
	## awk NF: last field
	swaylock_status=$(ps -ef | \
	    grep -v ^root | \
	    grep 'swayidle -w' | \
	    grep 'dimr' | \
	    awk -F : '{print $4}' | \
	    awk 'NF>1{print $NF}')
    }


    swaylock_exec()
    {
	sh $lock
	#sh $XDG_CONFIG_HOME/sway/code/lock
    }


    screen_off_exec()
    {
    	swaylock_status

	# [Sway - ArchWiki](https://wiki.archlinux.org/title/Sway#Idle)
	# lock the screen before suspending and pause any playing media
	#swayidle -w \
	#	 before-sleep 'playerctl pause' \
	#	 before-sleep 'swaylock'

	if [[ "$swaylock_status" == "no_swaylock" ]]; then

	    pkill swayidle

	    swayidle -w \
	        timeout 1   'swaymsg "output * power off"' \
	        resume	    'swaymsg "output * power on"; $($dimr swaylock_disable)'

	elif [[ "$swaylock_status" == "swaylock" ]]; then

	    pkill swayidle

	    swayidle -w \
	        timeout 1   'swaymsg "output * power off"' \
	        resume	    'swaymsg "output * power on"; $($dimr swaylock_enable $idle_time)'

	else

	    # undefined or other swaylock_status
	    pkill swayidle

	    swayidle -w \
	        timeout 1   'swaymsg "output * power off"' \
	        resume	    'swaymsg "output * power on"'

	fi
    }


    swaylock_enable()
    {
	pkill swayidle

        swayidle -w \
	    timeout $(( 1 * idle_time )) \
	        'swaymsg "output * $(feh --fullscreen /home/oxo/.cache/temp/lock.png)"' \
	        resume          'pkill feh'

	    timeout $(( 2 * idle_time )) \
		'$($dimr swaylock)'
		#'swaymsg "output * power on"; $(dimr swaylock)' \

	    timeout $(( 3 * idle_time )) \
		'swaymsg "output * power off"' \
	        resume	        'swaymsg "output * power on"' \
	        after-resume    'notify-send "swaylock enabled $idle_time"' \

	    timeout $(( 4 * idle_time )) \
		'$(sudo systemctl suspend)' \
	        before-sleep    '$($dimr swaylock)' & \
	                        'playerctl pause' & \
				'notify-send "swaylock enabled $idle_time"'
    }


    swaylock_disable()
    {
	pkill swayidle

	swayidle -w \
	    timeout $(( 1 * idle_time )) \
	        'swaymsg "output * power off"' \
                resume		'swaymsg "output * power on"' \
	        before-sleep	'$($dimr no_swaylock)' & \
				'notify-send "swaylock disabled"'
    }


    case "$option" in

	swaylock)
	    ## immediate swaylock
	    swaylock_exec
	    ;;

	screen_off)
	    ## immediate screen off
	    screen_off_exec
	    ;;

	swaylock_disable)
	    ## disable swaylock
	    swaylock_disable
	    ;;

        swaylock_enable | *)
	    ## enable swaylock
	    swaylock_enable
            ;;

    esac

    exit 0
}
