#! /usr/bin/env sh


csc="$XDG_CONFIG_HOME/sway/code"


set_params()
{
    monitor_dimensions=$(
	swaymsg -t get_workspaces |
	    jq -r '.. | select(.focused?) |
	    select(.type=="workspace") |
	    .rect |
	    "\(.width)x\(.height)"' \
		      )

    monitor_width=${monitor_dimensions%x*}
    monitor_height=${monitor_dimensions#*x}

    selection=".focused?"
    criteria=
    [[ "$id" ]] && \
	{
	    selection=".id == $id"
	    criteria="[con_id = $id]"
	}

    mapfile -t window_params_arr < <( \
	swaymsg -t get_tree | \
	    jq -r ".. |
	    select(.type?) |
	    select($selection) |
	    .rect.x, .rect.y,
	    .rect.width, .rect.height,
	    .deco_rect.height, .type" \
		)

    container_curr_position=($(
	swaymsg -t get_tree |
	    jq -r '.. | select(.type?) |
	    select(.focused?) |
	    .rect |
	    "\(.x) \(.y)"' \
		      ))

    new_x=${window_params_arr[0]}
    new_y=${window_params_arr[1]}
    window_width=${window_params_arr[2]}
    window_height=${window_params_arr[3]}
    decor_height=${window_params_arr[4]}
    window_type=${window_params_arr[5]}
}


horizontal_fill()
{
    divisor=4

    #set_width=$(echo "scale=0; $monitor_width"/"$divisor" | bc)
    set_height=$(echo "scale=0; $monitor_height"/"$divisor" | bc)

    con_focused_x=${container_curr_position[0]}
    con_focused_y=${container_curr_position[1]}

    # hide or dock (visible)
    bar_mode=$(swaymsg -rt get_bar_config bar-0 | jq -r '.mode')

    if [[ $bar_mode == 'dock' ]]; then

	# sway-ipc - interprocess communication (IPC) protocol for sway
	bar_height=$(swaymsg -rt get_bar_config bar-0 | jq -r '.bar_height')

	case $con_focused_y in

	    $bar_height)
		#snap to bottom screen border
		snap_toggle='S'
		;;

	    *)
		#snap to top screen border
		snap_toggle='N'
		;;

	esac

    else

	case $con_focused_y in

	    0)
		#snap to bottom screen border
		snap_toggle='S'
		;;

	    *)
		#snap to top screen border
		snap_toggle='N'
		;;

	esac

    fi

    swaymsg "${criteria}resize set width $monitor_width px height $set_height px"
    sh $csc/snap-move-to $snap_toggle
}


main()
{
    set_params
    horizontal_fill
}

main
