#! /usr/bin/env sh


csc="$XDG_CONFIG_HOME/sway/code"


set_params()
{
    monitor_dimensions=$(
	swaymsg -t get_workspaces |
	    jq -r '.. | select(.focused?) |
	    select(.type=="workspace") |
	    .rect |
	    "\(.width)x\(.height)"' \
		      )

    monitor_width=${monitor_dimensions%x*}
    monitor_height=${monitor_dimensions#*x}

    selection=".focused?"
    criteria=
    [[ "$id" ]] && \
	{
	    selection=".id == $id"
	    criteria="[con_id = $id]"
	}

    mapfile -t window_params_arr < <( \
	swaymsg -t get_tree | \
	    jq -r ".. |
	    select(.type?) |
	    select($selection) |
	    .rect.x, .rect.y,
	    .rect.width, .rect.height,
	    .deco_rect.height, .type" \
		)

    container_curr_position=($(
	swaymsg -t get_tree |
	    jq -r '.. | select(.type?) |
	    select(.focused?) |
	    .rect |
	    "\(.x) \(.y)"' \
		      ))

    new_x=${window_params_arr[0]}
    new_y=${window_params_arr[1]}
    window_width=${window_params_arr[2]}
    window_height=${window_params_arr[3]}
    decor_height=${window_params_arr[4]}
    window_type=${window_params_arr[5]}
}


vertical_fill()
{
    divisor=4

    set_width=$(echo "scale=0; $monitor_width"/"$divisor" | bc)
    #set_height=$(echo "scale=0; $monitor_height"/"$divisor" | bc)

    con_focused_x=${container_curr_position[0]}
    con_focused_y=${container_curr_position[1]}

    case $con_focused_x in

	0)
	    #snap to right screen border
	    snap_toggle='E'
	    ;;

	*)
	    #snap to left screen border
	    snap_toggle='W'
	    ;;

    esac

    swaymsg "${criteria}resize set width $set_width px height $monitor_height px"
    sh $csc/snap-move-to $snap_toggle
}


main()
{
    set_params
    vertical_fill
}

main
