#! /usr/bin/env sh

set_params()
{
    monitor_dimensions=$(
	swaymsg -t get_workspaces |
	    jq -r '.. | select(.focused?) |
	    select(.type=="workspace") |
	    .rect |
	    "\(.width)x\(.height)"' \
		      )

    monitor_width=${monitor_dimensions%x*}
    monitor_height=${monitor_dimensions#*x}

    selection=".focused?"
    criteria=
    [[ "$id" ]] && \
	{
	    selection=".id == $id"
	    criteria="[con_id = $id]"
	}

    mapfile -t window_params_arr < <( \
	swaymsg -t get_tree | \
	    jq -r ".. |
	    select(.type?) |
	    select($selection) |
	    .rect.x, .rect.y,
	    .rect.width, .rect.height,
	    .deco_rect.height, .type" \
		)

    new_x=${window_params_arr[0]}
    new_y=${window_params_arr[1]}
    window_width=${window_params_arr[2]}
    window_height=${window_params_arr[3]}
    decor_height=${window_params_arr[4]}
    window_type=${window_params_arr[5]}
}


quarterize()
{
    divisor=2

    set_width=$(echo "scale=0; $monitor_width"/"$divisor" | bc)
    set_height=$(echo "scale=0; $monitor_height"/"$divisor" | bc)

    swaymsg "${criteria}resize set width $set_width px height $set_height px"
}


main()
{
    set_params
    quarterize
}

main
