#! /usr/bin/env sh

formatted_ts_arr=()
timestamp=$(date +%s.%N)
## get focused container id
#prev_focus=$(swaymsg -r -t get_seats | jq '.[0].focus')
#ppid=$(ps -p $$ -o ppid=)
#printf "DEV$LINENO %s\n" "${ppid}"

## dtx (hexadecimal epoch)
formatted_ts_arr+=$(printf '%s_%X\n' "$(date -d @"$timestamp" $DT)" "$(date -d @"$timestamp" +'%s')")

## define a list of strftime formats
## text oriented formats have a trailing space
formats_strftime_arr=(
    "%s.%N"
    "%d/%m/%Y %H:%M "
    "%Y-%m-%dT%H:%M:%S%z_%Z "
    "%A %d %B %Y "
    "week %V %Y"
)

for format in "${formats_strftime_arr[@]}"; do

    date_formatted=$(date -d @"$timestamp" +"$format")

    formatted_ts_arr+=("$date_formatted")

done

## select a format
timestamp_selected=$(printf "%s\n" "${formatted_ts_arr[@]}" \
			 | fzf --header="select timestamp format:")

wl-copy -n <<<$timestamp_selected && notify-send "timestamp copied $(date +'%S')"

#swaymsg focus next child
#swaymsg focus next parent
#swaymsg focus prev child
#swaymsg focus prev parent

# swaymsg kill
# swaymsg "[con_id=$prev_focus]" focus
#kill -TERM $ppid

#wl-paste


#swaymsg -m -t subscribe '["window"]' | \
#  jq --unbuffered 'select(.change == "focus").container.id' | \
#  while read new_focus; do
#    swaymsg "[con_id=${prev_focus}] mark --add _prev" &>/dev/null
#    prev_focus=$new_focus
#  done

#TODO DEV directly insert when zsh is active
#LBUFFER+="$timestamp_selected"
#BUFFER="$timestamp_selected" && zle vi-add-eol
