#! /usr/bin/env sh

cgnc="$XDG_DATA_HOME/c/git/note/catalog"

## generate catalog list
sh "$cgnc/generate"

## define catalog source
catalog="$cgnc/list"

## NOTICE
## sed removes first word and remaining leading spaces
## second sed removes '  ## '-marked comments
## add a trailing space by adding '\ ' to the replace part of sed
cat $catalog | \
    fzf --height ~100% | \
    sed 's/[^ ]* *//' | \
    sed 's/  ## .*$//' | \
    sed 's/  \/\/ .*$//' | \
    wl-copy -n
