#! /usr/bin/env sh

formatted_ts_arr=()
timestamp=$(date +%s.%N)

## dtx (hexadecimal epoch)
formatted_ts_arr+=$(printf '%s_%X\n' "$(date -d @"$timestamp" $DT)" "$(date -d @"$timestamp" +'%s')")

## define a list of strftime formats
## text oriented formats have a trailing space
formats_strftime_arr=(
    "%s.%N"
    "%d/%m/%Y %H:%M "
    "%Y-%m-%dT%H:%M:%S%z_%Z "
    "%A %d %B %Y "
    "week %V %Y"
)

for format in "${formats_strftime_arr[@]}"; do

    date_formatted=$(date -d @"$timestamp" +"$format")

    formatted_ts_arr+=("$date_formatted")

done

## select a format
timestamp_selected=$(printf "%s\n" "${formatted_ts_arr[@]}" \
    | fzf --header="select timestamp format:" \
    | wl-copy -n && notify-send 'timestamp copied')


#TODO DEV directly insert when zsh is active
#LBUFFER+="$timestamp_selected"
#BUFFER="$timestamp_selected" && zle vi-add-eol
