#! /usr/bin/env sh

## NOTICE sed is used to remove '  ## '-marked comments from the lines
spicules=$(\
	cat $XDG_DATA_HOME/c/git/note/linux/shell/command/catalog | \
	fzf --height ~100% | \
	sed 's/  ## .*$//' | \
	#sed 's/  ## .*$//' \
	wl-copy
	    #> $XDG_CACHE_HOME/cb\
)

swaymsg -t command exec $spicules
