#! /usr/bin/env sh
#
##
###                                      _ _
###  _____      ____ _ _   _    _____  _(_) |_
### / __\ \ /\ / / _` | | | |  / _ \ \/ / | __|
### \__ \\ V  V / (_| | |_| | |  __/>  <| | |_
### |___/ \_/\_/ \__,_|\__, |  \___/_/\_\_|\__|
###                    |___/
### # # # # # #
###      #
### # # # # # #
###
### sway exit
### terminal cli application that offers a sway fzf exit dialogue
### (c) 2019 - 2023  |  oxo
###
##
#


sway_ver=$(sway -v | sed 's/ersion //')

exit_option=$(printf \
	" cancel \n idle \n lock \n exit \n suspend \n reboot \n poweroff " | \
	fzf \
	--prompt="  E X I T ? $(printf '%s' "$sway_ver") "
	)


cancel() {

	exit

}


sway_idle() {

	sh $XDG_CONFIG_HOME/code/sway/dimr screen_off

}


sway_lock() {

	sh $XDG_CONFIG_HOME/code/sway/dimr swaylock_now

}


sway_exit() {

	sway exit

}


os_suspend() {

	systemctl suspend

}


os_reboot() {

	systemctl reboot

}


os_poweroff() {

	systemctl poweroff

}


case $exit_option in

	*cancel*)
		exit 0
		;;

	*idle*)
		sway_idle
		;;

	*lock*)
		sway_lock
		;;

	*exit*)
		sway_exit
		;;

	*suspend*)
		os_suspend
		;;

	*reboot*)
		os_reboot
		;;

	*poweroff*)
		os_poweroff
		;;

	*)
		exit 111
		;;

esac


#swaymsg -t command exec $exit_option
