#! /usr/bin/env sh
: '
            _         _
  ___ _ __ | |__   __| |
 / __| '_ \| '_ \ / _` |
| (__| |_) | |_) | (_| |
 \___| .__/|_.__/ \__,_|
     |_|
 _    _
(_)><(_)

cpbd
clipboard list
manage multiple copied items
WARNING not intended for use with sensitive data!

usage:
    add wl-copy to clipboard list:
	1. select items
	2. wl-copy	C-S-c
	3. cpbd_add	C-S-y

    put clipboard list to wl-copy:
	1. put		C-S-p
	2. fzf select
	3. wl-paste	C-S-v

    remove items from clipboard list:
	cpbd_remove	C-S-r
	fzf select

    clear entire clipboard list:
	cpbd_clear	C-S-M-r

keybinds defined in sway config
# '


arg=$1


remove_empty_lines()
{
    sed -i '/^[[:space:]]*$/d' $XDG_CACHE_HOME/cpbd
}


remove_duplicates()
{
    sort -u $XDG_CACHE_HOME/cpbd > $XDG_CACHE_HOME/cpbd_updated
    replace_cpbd_file
}


replace_cpbd_file()
{
    mv -f $XDG_CACHE_HOME/cpbd_updated $XDG_CACHE_HOME/cpbd
}


## add current wl-clipboard item to cpbd_file (clipboard list)
add()
{
    cp_item=$(wl-paste)

    lines_add=$(echo "$cp_item" | wc -l)

    # do not add empty lines
    case $cp_item in

	''|'\n')
	    :
	    ;;

	*)
	    wl-paste >> $XDG_CACHE_HOME/cpbd
	    notify-send "cpbd: added $lines_add lines to list"
	    ;;

    esac

    unset cp_item
    unset lines_add

    remove_empty_lines
    remove_duplicates
}


## put items from cpbd to wl-copy
put()
{
    put_exec=$(cat $XDG_CACHE_HOME/cpbd | fzf -m --prompt='put to wl-copy ' | tr '\n' ' ' | wl-copy)

    lines_put=$(echo "$put_exec" | wc -l)

    swaymsg -t command exec $put_exec

    notify-send "cpdb: put $lines_put lines to wl-copy"

    unset put_exec
    unset lines_put
}


## remove selected item(s) from cpbd
remove_item()
{
    remove_item_exec=$(cat $XDG_CACHE_HOME/cpbd | fzf -m --prompt='remove from list ')

    lines_remove=$(echo "$remove_item_exec" | wc -l)

    while IFS= read -r line; do

	grep --invert-match --line-regexp "$line" $XDG_CACHE_HOME/cpbd > $XDG_CACHE_HOME/cpbd_updated

	replace_cpbd_file

    done <<< "$remove_item_exec"

    notify-send "cpdb: removed $lines_remove lines from list"

    unset remove_item_exec
    unset lines_remove
}


## remove all item(s) from cpbd
remove_all()
{
    rm $XDG_CACHE_HOME/cpbd

    notify-send "cpbd: removed list"
}


main()
{
    case $arg in

	add)
	    add
	    ;;

	put)
	    put
	    ;;

	remove_item)
	    remove_item
	    ;;

	remove_all)
	    remove_all
	    ;;

    esac
}

main
