#! /usr/bin/env sh

catalog="$XDG_DATA_HOME/c/git/note/linux/shell/command/catalog"

## NOTICE sed is used to remove '  ## '-marked comments from the lines
## add a trailing space by adding '\ ' to the replace part of sed

cat $catalog | \
    fzf --height ~100% | \
    sed 's/  ## .*$//' | \
    wl-copy -n

wl-paste -n
