#! /usr/bin/env sh

## take screenshot, desaturate and displace image

csc="$XDG_CONFIG_HOME/sway/code"
lock_bg="$XDG_CACHE_HOME/temp/lock_bg.png"
lock_bg_desat="$XDG_CACHE_HOME/temp/lock_bg_desat.png"


# screenshot

grim -o $(swaymsg -t get_outputs \
	| jq -r '.[] | select (.focused) | .name') \
	"$lock_bg"
wait

# desaturate

image_in="$lock_bg"
image_out="$image_in"
convert -modulate 100,25,100 "$image_in" "$image_in"
wait

# screen blur

## overwrite original screenshot
image_out="$image_in"

sh $csc/lock_scr_eff -r -s 3.5 -t displace -a 10 -m 1 "$image_in" "$image_out"
