#! /usr/bin/env sh


# solid black background

#swaylock --config "$XDG_CONFIG_HOME/sway/lock/config"


# OR


# screeneffect background

#: '
csc="$XDG_CONFIG_HOME/sway/code"
sh $csc/lock-make-bg
wait
swaylock --config "$XDG_CONFIG_HOME/sway/lock/config-bg"
# '
