#! /usr/bin/env sh

# split_fallback

# fallback to default sway split toggle status (splith/v)

default_split='splitv'

## revert to default_split after 3 seconds
fb_delay=30

# Reset $SECONDS; counting of seconds will (re)start from 0(-ish).
SECONDS=0

while (( SECONDS < fb_delay )); do

    :

done

swaymsg $default_split
nfsm='splitv (beside)'

## show time reference
## i keep forget that
## notify-send spawns from the top
## highest is newest
## and has the highest time reference
ts="$(date '+%s%N' | cut -c 9-11)"
#notify-send -- "$ts default $nfsm"
