#!/usr/bin/env sh

# dependencies:	jq, alacritty

# let sway spawn a new terminal window in the cwd

terminal_cmd="alacritty"


# get focused process ID

focused_pid=""
focused_pid="$(swaymsg -t get_tree | \
    jq '.. |
    select(.type?) |
    select(.type=="con") |
    select(.focused==true).pid')"


# readlink from focused ppid cwd

## check if $focused_pid is an integer
if [ "$focused_pid" -eq "$focused_pid" 2>/dev/null ]; then

    ## get focused parent process ID
    focused_ppid="$(ps -o pid= --ppid "$focused_pid" | awk '{print $1}')"

    ## get focused present working directory
    focused_pwd=""
    if [ "$focused_ppid" 2>/dev/null ]; then

	focused_pwd="$(readlink "/proc/$focused_ppid/cwd")"

    fi

fi


# spawn terminal

## ceck if directory exists
if [ -d "$focused_pwd" ]; then

    $terminal_cmd --working-directory="$focused_pwd" $@ &

else

    exit 48
    #$terminal_cmd $@ &
    #printf 'error finding ${RED}%s${NOC}\n' "$focused_pwd"

fi

# under here can probably been deleted
# [TODO] take over priviledge escalation status
#sudo -n printf "" > /dev/null 2>&1
