#! /usr/bin/env sh

###  _                           __             _           _
### | |_ ___ _ __ _ __ ___      / _| ___  _ __ | |_     ___(_)_______
### | __/ _ \ '__| '_ ` _ \    | |_ / _ \| '_ \| __|   / __| |_  / _ \
### | ||  __/ |  | | | | | |   |  _| (_) | | | | |_    \__ \ |/ /  __/
###  \__\___|_|  |_| |_| |_|___|_|  \___/|_| |_|\__|___|___/_/___\___|
###                       |_____|                 |_____|
###
###  # # # # # #
###       #
###  # # # # # #
###

: '
term_font_size
set alacritty terminal font size (for screencasts)
(c) 2019 - 2024  |  oxo

GNU GPLv3 GENERAL PUBLIC LICENSE
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
https://www.gnu.org/licenses/gpl-3.0.txt

@oxo@qoto.org


# dependencies
  jq, alacritty

# usage
  % term_font_size [point_size]

# examples
  n/a

# '


specific_point_size=$1

if [ -n $1 ]; then

    alacritty msg config font.size=$specific_point_size

else

    alacritty msg config font.size=11

fi
