#! /usr/bin/env sh

## bluetooth
bt_status=$(systemctl status bluetooth | grep active | awk '{print $2}')

if [ "$bt_status" = 'active' ]; then

    bt='B'
    #bt_block=$(printf '%s\n' 'B')

fi

echo "${bt}"
