#! /usr/bin/env sh

## clst file
if [[ -f $XDG_CACHE_HOME/clst ]]; then

    clst_lines=$(wc -l $XDG_CACHE_HOME/clst | awk '{print $1}')

    if [[ $clst_lines -gt 0 ]]; then

        clst=$clst_lines

    fi
        
fi


## bluetooth
bt_status=$(systemctl status bluetooth | grep active | awk '{print $2}')

if [ "$bt_status" = 'active' ]; then

    bt='B'
    #bt_block=$(printf '%s\n' 'B')

fi

echo "${clst}${bt}"
