#! /usr/bin/env sh


csbe="$XDG_CONFIG_HOME/status/bar/element"
source $csbe/get-focus-data


## focused workspace must have at least one container
if [[ $container_pid != 'null' ]]; then

    # NOTICE mandatory eol for i3blocks
    printf '%s %s\n' "$container_type_bar" "$container_name"

fi
