#! /usr/bin/env sh


bar_el_dir="$XDG_CONFIG_HOME/status/bar/element"
source $bar_el_dir/get_focus_data


# NOTICE mandatory eol for i3blocks
if [[ -n $con_pid ]]; then

    printf '%s %s\n' "$con_type_bar" "$con_name"

fi
