#! /usr/bin/env sh

# sway-output monitor origo O(0.0) NW
# sway-output container origo O(0.0) NW
# dotool monitor origo O(0.0) NW

monitor_data ()
{
    # retrieve focused monitor data

    monitor_focus_data=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused==true) | "\(.id),\(.name),\(.serial),\(.rect.width),\(.rect.height),\(.make),\(.model)"')

    ## string to array
    IFS=',' read -r -a monitor_data_arr <<< "$monitor_focus_data"

    ## set monitor variables
    monitor_id=${monitor_data_arr[0]}
    monitor_name=${monitor_data_arr[1]}
    monitor_serial=${monitor_data_arr[2]}
    monitor_width=${monitor_data_arr[3]}
    monitor_height=${monitor_data_arr[4]}
    monitor_make=${monitor_data_arr[5]}
    monitor_model=${monitor_data_arr[6]}

    monitor_name_bar=$(printf '%s' "$monitor_name" | sed 's/"//g' | head -c 1)
}


workspace_data ()
{
    # retrieve focused workspace data

    workspace_focus_data=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused == true)')

    workspace_name=$(printf '%s' "$workspace_focus_data" | jq '.name')
    workspace_name_bar=$(printf '%s' "$workspace_focus_data" | jq '.name' | sed 's/"//g')
}


swaybar_data ()
{
    bar_id=$(swaymsg -t get_bar_config | grep 'bar' | cut -d '"' -f 2)
    bar_height=$(swaymsg -t get_bar_config "$bar_id" |  jq '.bar_height')
}


container_data ()
{
    # retrieve focused container data

    container_focus_data=$(swaymsg -t get_tree | jq -r '.. | select(.type?) | select(.focused == true) | "\(.id),\(.pid),\(.type),\(.name),\(.rect.x),\(.rect.y),\(.rect.width),\(.rect.height),\(.deco_rect.width),\(.deco_rect.height)"')


    ## string to array
    IFS=',' read -r -a container_data_arr <<< "$container_focus_data"

    ## set container variables
    container_id=${container_data_arr[0]}
    container_pid=${container_data_arr[1]}
    container_type=${container_data_arr[2]}
    container_name=${container_data_arr[3]}
    container_x=${container_data_arr[4]}
    container_y=${container_data_arr[5]}
    container_width=${container_data_arr[6]}
    container_height=${container_data_arr[7]}
    container_deco_width=${container_data_arr[8]}
    container_deco_height=${container_data_arr[9]}

    ## container types
    ### []= tiling
    ### <>= floating
    ### <M> monoocle
    ###      (maximized floating container)

    case $container_type in

	'con')
	    container_type_bar='[]='
	    ;;

	'floating_con')
	    container_type_bar='<>='

	    [[ $monitor_width == $container_width ]] && \
		[[ $(( monitor_height + bar_height )) == $monitor_height ]] && \
		container_type_bar='<M>'
	    ;;

	*)
	    # i.e. workspace
	    container_type_bar=''
	    ;;

    esac
}


main ()
{
    monitor_data
    workspace_data
    swaybar_data
    container_data
}

main
