#! /usr/bin/env sh

ip='9.9.9.9'

# name active interface
if [[ -n $(ip route show) ]]; then

    ## perl regex positive look-ahead
    ## [Using Look-ahead and Look-behind](https://www.perlmonks.org/?node_id=518444)
    i=$(ip route get $ip | grep --perl-regexp --only-matching --ignore-case --word-regexp '(?<=\bdev )([a-zA-Z0-9-])+')

fi

# full text
echo "$i"

## short text
echo  ## none

## text
case $i in

    wg-*)
	echo "#529877"  ## dark moderate cyan - lime green
	;;

    *)
	echo  ## default
	;;

esac

## background
echo  ## default

## border
echo  ## default
