#! /usr/bin/env sh

ip='9.9.9.9'
wg_designator='wg*'

# name active interface
if [[ -n $(ip route show) ]]; then

    ## perl regex positive look-ahead
    ## [Using Look-ahead and Look-behind](https://www.perlmonks.org/?node_id=518444)
    i=$(ip route get $ip | grep --perl-regexp --only-matching --ignore-case --word-regexp '(?<=\bdev )([a-zA-Z0-9-])+')

else

    ## no active interface
    i=0i

fi

# full text
echo "$i"

## short text
echo  ## none

## text
case $i in

    $wg_designator )
	echo  ## default
	;;

    * )
	## white   abnormal operation
	echo "#ffffff"
	;;

esac

## background
case $i in

    $wg_designator )
	echo  ## default
	;;

    * )
	## black   abnormal operation
	echo "#000000"
	;;

esac

## border
echo  ## default
