#!/bin/sh

if [[ -n $(ip route show) ]]; then

	ipex4=$(host myip.opendns.com resolver1.opendns.com | \
		tail -n 1 | rev | cut -d ' ' -f 1 | rev)
	ipex6=$(ip a | grep inet6 | grep -v fe80 | awk '{print $2}')
	# fe80:* is a local ipv6 address block

	#ipex=$(dig @resolver1.opendns.com myip.opendns.com +short)
	#exip=$(dig myip.quad9.net @9.9.9.9 +short)
	#exip=$(curl -4 https://ident.me)
	#exip=$(curl -4 http://ident.me)
	#exip=$(wget -qqO- 'https://duckduckgo.com/?q=what+is+my+ip' |\
	#	grep -Pow 'Your IP address is \K[0-9.]+')

	case $ipex4 in

		A)
			# we have an ipv6 public address
			# ipex4: host has no A record
			ipex=$ipex6
			;;

		*)
			# we have an ipv4 public address
			ipex=$ipex4
			;;

	esac


	printf '%s\n' "$ipex"
	#echo $ipex
fi
