#! /usr/bin/env sh

bar_el_dir="$XDG_CONFIG_HOME/status/bar/element"
source $bar_el_dir/get_focus_data

## NOTICE eol for i3blocks
if [[ -n $monitor_name ]]; then

    printf '%s %s%s %s\n' "$con_pid" "$monitor_name_bar" "$workspace_name_bar" "$con_id"

fi
