#! /usr/bin/env sh


csbe="$XDG_CONFIG_HOME/status/bar/element"
source $csbe/get-focus-data


if [[ -n $monitor_name ]]; then

    [[ $container_pid != 'null' ]] && printf '%s %s ' "$container_pid" "$container_id"
    ## NOTICE eol for i3blocks
    printf '%s%s\n' "$monitor_name_bar" "$workspace_name_bar"

fi
