#! /usr/bin/env sh

: '
##[TODO] posix compliance:
#/bin/sh does not accept the array

# set clock divider sign
sync=$(timedatectl | grep sync | awk '{print $4}')

if [[ "$sync" = "yes" ]]; then

	divider=(':' '·' ':' '.')

else

	divider=('!' '.' '!' '.')

fi


cnt=0

while true; do
#while [ -n "$SWAYSOCK" ]; do

	loc=$(($cnt % 4))

	cnt=$(($cnt + 1))

	echo $(date "+%H${divider[$loc]}%M")
	#echo $(date "+%u%d %H${divider[$loc]}%M")

	sleep 2

done
# '

# man 3 strffime

#TODO via environment variables
TWDN1='m t w h f s u'
weekday_name=$(cut -d ' ' -f "$(date +'%u')" <<< $TWDN1)
day_of_month=$(date '+%d')
time_hms=$(date '+%H%M%S')
# time_hms=$(date '+%u%d %H%M%S')

echo "${weekday_name}${day_of_month} ${time_hms}"
