#! /usr/bin/env sh

: '
##[TODO] posix compliance:
#/bin/sh does not accept the array

# set clock divider sign
sync=$(timedatectl | grep sync | awk '{print $4}')

if [[ "$sync" = "yes" ]]; then

	divider=(':' '·' ':' '.')

else

	divider=('!' '.' '!' '.')

fi


cnt=0

while true; do
#while [ -n "$SWAYSOCK" ]; do

	loc=$(($cnt % 4))

	cnt=$(($cnt + 1))

	echo $(date "+%H${divider[$loc]}%M")
	#echo $(date "+%u%d %H${divider[$loc]}%M")

	sleep 2

done
# '

second=$(date "+%S")

# simple clock (HHMM)
#printf '%s\n' "$hour$minute"
#echo $hour$minute
#echo $hour$minute$second

## full text
echo $second

## short text
echo

## color echo text background border
#if [[ $(( second % 2 )) -eq 0 ]]; then
#
#    ## text
#    echo "#999999"
#
#    ## background
#    echo
#
#    ## border
#    echo
#
#else
#
#    ## text
#    echo "#777777"
#
#    ## background
#    echo
#
#    ## border
#    echo
#
#fi
