#! /usr/bin/env sh

## focused container data block
focused_con_data=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused == true)')

pid=$(printf '%s' "$focused_con_data" | jq ' .pid' | sed 's/null//')
name=$(printf '%s' "$focused_con_data" | jq ' .name' | sed 's/"//g')

type=$(printf '%s' "$focused_con_data" | jq ' .type')
[[ $type == '"con"' ]] || con_type='~' || con_type='=<>'
#[[ $type == '"con"' ]] && con_type='=[]' || con_type='=<>'

# NOTICE eol for i3blocks
if [[ -n $pid ]]; then

    printf '%s %s %s\n' "$name" $pid "$con_type"
    #printf '%s %6s %s\n' "$name" $pid "$con_type"

fi
