#!/bin/sh
##
###
### spicules
### fuzzy search command catalogue
###
### 2018 - 2021 cytopyge
##
#

sourcefile="$XDG_DATA_HOME/git/notes/linux/shell/cmd_cat"

spicules=$(cat $sourcefile | \
	bemenu \
	--ignorecase \
	--wrap \
	--no-overlap \
	--list=25 \
	--prompt "cmd_cat" \
	--monitor=all \
	--line-height=0 \
	--tf=#ff73fd \
	--tb=#000000 \
	--ff=#999999 \
	--fb=#000000 \
	--hf=#96cbfe \
	--hb=#000000 \
	--nf=#666666 \
	--nb=#000000
	)

	# no comments inside settings
	# state: 'bg', 'fg', 'bgalt', 'hlbg', 'hlfg'
	# 'background', 'border', 'separator'

[ -z $spicules ] && exit

echo -n $spicules | wl-copy
