#!/bin/bash

# usage: pull_all [git_repo_mon_list_location]

## hardcoded variables
source_repo='origin/main'
source_dir="$XDG_DATA_HOME/c/git/code/source/function"

## user authentication
source "$source_dir/get_sudo"
get_sudo

## get location grml
if [[ -z $1 ]]; then

	git_repo_mon_list="$XDG_CONFIG_HOME/git/git_repo_mon_list"

else

	git_repo_mon_list="$1"

fi


get_git_pwd() {
    passr codeberg_oxo peacto
    #pass show codeberg_oxo | grep peacto | awk '{print $2}' | wl-copy -o
}


while read line; do

	cd $line
	echo
	pwd
	git_status=$(git status -sb)
	printf "$git_status\n"

	git pull

done < $git_repo_mon_list
