#! /usr/bin/env sh

code_dir="$XDG_CONFIG_HOME/status/bar/element"

info_tool='ipex macex interface macin ipin vrx vtx mem bt temp cpu vol brightness batt weather time'

tput civis

for i in $info_tool; do

    ## sed to remove any i3blocks color coding
    info=$(sh $code_dir/$i | sed 's/^#[0-9]\{6\}//')

    : '
    ## DEV if no info
    case $info in

	'')
	    printf "$i "
	    ;;

    esac
    # '

    ## special formatting
    ## managing symbols, grouping. spaces & EOL's
    case $i in

	temp)
	    printf '%s' "$info"
	    ;;

	brightness )
	    printf '%s%%' "$info"
	    ;;

	vol | audio_source | batt_perc | time )
	    printf '%s' "$info"
	    ;;

	* )
	    printf '%s' "$info "
	    ;;

    esac

done

echo

tput cnorm
