#!/bin/bash

#[TODO] posix compliant #!/bin/sh does not accept the array

## set clock divider sign
sync=$(timedatectl | grep sync | awk '{print $4}')
if [ "$sync" = "yes" ]; then
    divider=(':' '·' ':' '.')
else
    divider=('!' '.' '!' '.')
fi

cnt=0

while true; do
#while [ -n "$SWAYSOCK" ]; do

	loc=$(($cnt % 4))

	cnt=$(($cnt + 1))

	echo $(date "+%u%d %H${divider[$loc]}%M")

	sleep 2

done
