#!/bin/sh

#
##
###					     _
###  _ __ _ __   __ _      _ __   ___   ___ | |
### | '__| '_ \ / _` |    | '_ \ / _ \ / _ \| |
### | |  | | | | (_| |    | |_) | (_) | (_) | |
### |_|  |_| |_|\__, |____| .__/ \___/ \___/|_|
###             |___/_____|_|
###  _    _
### (_)><(_)
###
### rng_pool
### random number generator entropy pool availability indicator
###
### (c) 2019 - 2022 oxo
###
### note:
### before linux kernel 5.18 poolsize was 1024
### after linux kernel 5.18 poolsize is 256
##
#

#pool=$(cat /proc/sys/kernel/random/poolsize)
avail=$(cat /proc/sys/kernel/random/entropy_avail)

#perc=$(($avail*100/$pool))

if [ $avail -lt 128 ]; then
	printf "%.0fb\n" $avail
fi
