#!/bin/sh

treshold_perc=80
# shows >80% when one of the (virtual) blockdevices fsuse reporting more than 80%

fsuse=$(lsblk -o fsuse%,name,fsused,size --raw --noheadings | grep '%' | sort -nr)

perc_used=$(echo -e $fsuse | awk -F % '{print $1}')

while IFS=" " read -r line; do

	if [ $perc_used -ge $treshold_perc ]; then

	    printf "%s\n" ">$treshold_perc%"
		exit

	fi

done <<< "$fsuse"
