#!/bin/sh
#
##
###                                      _ _
###  _____      ____ _ _   _    _____  _(_) |_
### / __\ \ /\ / / _` | | | |  / _ \ \/ / | __|
### \__ \\ V  V / (_| | |_| | |  __/>  <| | |_
### |___/ \_/\_/ \__,_|\__, |  \___/_/\_\_|\__|
###                    |___/
###
###  _ _|_ _ ._    _  _
### (_\/|_(_)|_)\/(_|(/_
###   /      |  /  _|
###
### sway exit
### wofi application that offers options to exit sway
### (c) 2019 - 2020 cytopyge
###
##
#

exit=$(echo -e "cancel\nswaylock -F -c 000000\nsway exit\nsystemctl reboot\nsystemctl poweroff" | \
	wofi \
	--show=dmenu \
	--monitor=0 \
	--location=top \
	--width=100% \
	--lines=1 \
	--columns=5 \
	--hide-scroll \
	--insensitive \
	--matching=fuzzy \
	--gtk-dark \
	--prompt="E X I T ?   $(sway -v) " \
	)

[ -z $exit ] && exit

`echo $exit`
