#!/bin/sh

exip=$(dig @resolver1.opendns.com myip.opendns.com +short)
#exip=$(dig myip.quad9.net @9.9.9.9 +short)
#exip=$(curl -4 https://ident.me)
#exip=$(curl -4 http://ident.me)
#exip=$(wget -qqO- 'https://duckduckgo.com/?q=what+is+my+ip' | grep -Pow 'Your IP address is \K[0-9.]+')


if [ ! -z "$exip" ]; then
	echo $exip
fi
