#!/bin/bash

#[TODO] posix compliant #!/bin/sh does not accept the array


i=$(ip -o -4 route show to default | awk '{print $5}')

# check for interface

if [ -z "$i" ]; then
	exit
fi


# rx 	received on interface (bytes)
# tx 	transmitted on interface (bytes)
# t	timestamp (nanoseconds (10^-9))

#rx0=$(cat /proc/net/dev | grep $i | awk '{print $2}')
tx0=$(cat /proc/net/dev | grep $i | awk '{print $10}')
t0=$(date +%s%N)

sleep 1

#rx1=$(cat /proc/net/dev | grep $i | awk '{print $2}')
tx1=$(cat /proc/net/dev | grep $i | awk '{print $10}')
t1=$(date +%s%N)


# drx	received on interface (kilobytes)
# dtx 	transmitted on interface (kilobytes)
# dt	elapsed time (seconds)

#drx=$((rx1-rx0))/1000
dtx=$((tx1-tx0))/1000
dt=$(((t1-t0)/1000000000))


# vrx	receive speed on interface (kbytes/s)
# vtx 	transmit speed on interface (kbytes/s)

#vrx=$(( drx / dt ))
vtx=$(( dtx / dt ))

printf "%4s\n" "$vtx"
[ ${vtx} -gt 500 ] && exit 33 || exit 0
