#!/usr/bin/env sh

# audio volume
master_volume=$(amixer -D pulse sget Master | grep 'Left: ' | cut -d ' ' -f 7 | tr -d -c "[:digit:]")
master_mute=$(amixer get Master | grep 'off')
#amixer -D pulse sget Master | grep 'Left: ' | awk -F '[][]' '{printf "%s",$2}'
printf '%s\n' "$volume"

# audio source
jack_status=$(grep -A 11 'Node 0x14' /proc/asound/card1/codec\#0 | grep ctls | awk '{print $2}')


output="<"
if [ "$jack_status" == "0x40:" ]; then

    # Node 0x14 Speaker Playback Switch
    # Pin-ctls: 0x00
    # -> headphones connected
    # Pin-ctls: 0x40<
    # -> no headphones connected
    output='H'

fi


mute=""
if [ -n "$master_mute" ]; then

    # Master Front Left Playback: [off]
    # master muted
    mute='x'

fi

audio=$master_volume$mute$output

echo $vol
