#!/usr/bin/env bash

user0=$(awk '/cpu / {print $2}' /proc/stat)
nice0=$(awk '/cpu / {print $3}' /proc/stat)
system0=$(awk '/cpu / {print $4}' /proc/stat)
idle0=$(awk '/cpu / {print $5}' /proc/stat)
iowait0=$(awk '/cpu / {print $6}' /proc/stat)
irq0=$(awk '/cpu / {print $7}' /proc/stat)
softirq0=$(awk '/cpu / {print $8}' /proc/stat)
steal0=$(awk '/cpu / {print $9}' /proc/stat)
guest0=$(awk '/cpu / {print $10}' /proc/stat)
guest_nice0=$(awk '/cpu / {print $11}' /proc/stat)

total_tick0=$((user0+nice0+system0+idle0+iowait0+irq0+softirq0+steal0+guest0+guest_nice0))
load0=$((total_tick0-idle0))

sleep 1

user1=$(awk '/cpu / {print $2}' /proc/stat)
nice1=$(awk '/cpu / {print $3}' /proc/stat)
system1=$(awk '/cpu / {print $4}' /proc/stat)
idle1=$(awk '/cpu / {print $5}' /proc/stat)
iowait1=$(awk '/cpu / {print $6}' /proc/stat)
irq1=$(awk '/cpu / {print $7}' /proc/stat)
softirq1=$(awk '/cpu / {print $8}' /proc/stat)
steal1=$(awk '/cpu / {print $9}' /proc/stat)
guest1=$(awk '/cpu / {print $10}' /proc/stat)
guest_nice1=$(awk '/cpu / {print $11}' /proc/stat)

total_tick1=$((user1+nice1+system1+idle1+iowait1+irq1+softirq1+steal1+guest1+guest_nice1))
load1=$((total_tick1-idle1))

cpu_perc=$((100*(load1-load0)/(total_tick1-total_tick0)))
cpu=$(printf "%02d" $cpu_perc)

#printf "%s\n" "$cpu"
echo $cpu
# echo text background border
# !! finer granularity than 2 stages causes unpredictable behaviour
[[ $cpu_perc -gt 50 ]] && exit 33
[[ $cpu_perc -gt 20 ]] && echo && echo "#ff73fd" #&& echo "#000000" #&& echo "#000000"

exit 0
