#! /usr/bin/env sh

###        _ _
###   __ _| (_) __ _
###  / _` | | |/ _` |
### | (_| | | | (_| |
###  \__,_|_|_|\__,_|
###
###
###  # # # # # #
###       #
###  # # # # # #
###

: '
alia
zsh environment alias and function definitions
copyright (c) 2019 - 2025  |  oxo

GNU GPLv3 GENERAL PUBLIC LICENSE
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
https://www.gnu.org/licenses/gpl-3.0.txt

@oxo@qoto.org


# dependencies
  n/a

# usage
  mitigate usage alias or function for command, execute:
  command $command_alias
  OR
  \$command_alias

# examples
  n/a

# '


# application behaviour

## sudo with trailing space;
## on expansion check next word for alias substitution
## therefore also 'sudo $cmd' lets $cmd expand to alias
alias sudo='sudo '


# function sudo ()
# {
#     ## invoke doas with sudo

#     ## sudo -k cannot be aliased
#     ## therefore solution below
#     case "$1" in

# 	-k )
# 	    doas -L
# 	    ;;

# 	* )
# 	    doas "$@"
# 	    ;;

#     esac
# }
# ## disable function sudo
# ## -f designates function definition instead of variable (-v)
# unset -f sudo


function host ()
{
    command cat /etc/hostname
}

## always sort printenv variable list
alias printenv='printenv | sort'


# less and less related

## define colors for error (Emk), search (Swk) & prompt (P15.0)
## https://en.wikipedia.org/wiki/ANSI_escape_code#SGR
alias less='less --mouse --no-init --quit-if-one-screen --status-column --long-prompt -P m"\ ?f%f:stdin .?L∑%L\ .?pt%pt\%\ .[?lt%lt-?lb%lb]\ ..?e[EOF]\ ." --use-color --color Emk --color SkW --color P15.0 -- "$@"'


## protect against shell command injection
### https://security.stackexchange.com/questions/56307/can-cat-ing-a-file-be-a-potential-security-risk/56323#56323
alias cat='bat'
#alias cat='cat --show-ends --show-nonprinting'
alias bat='bat --style plain "$@"'


## readnullcommand (READNULLCMD)
## command to assume if a single input redirection is specified with no command
## see zshenv for related READNULLCMD setting
## '< $file' behaviour
function read0cmd ()
{
    cat
    #less
}


## c (see) a file
## as < seems not to activate file completion and c is easier to type than <
## NOTICE combine with fzf-ins-pwd C-l for current directory
function c ()
{
    cat
}


## manpages
alias man='man --no-hyphenation --no-justification --prompt="$MANLESS"'
#alias eman='emacs -e '(man "$1")''


# vim

alias vi='nvim'
alias vim='nvim'
alias vimdiff='nvim -d'


# emacs

function emacs_daemon ()
{
    # if no active daemon, then start service

    #daemon_active=$(ls /run/user/1000/emacs >/dev/null 2>&1 | wc -l)
    emacs_active=$(systemctl --user status emacs.service \
                       | grep Active: \
                       | awk '{print $2}')

    case "$emacs_active" in

	failed | inactive )

	    printf 'starting emacs.service ...'
            systemctl --user start emacs.service
	    sleep 2
	    systemctl --user status emacs.service
            ;;

    esac
}

## [Emacs - ArchWiki](https://wiki.archlinux.org/title/Emacs#Multiplexing_emacs_and_emacsclient)

## CAUTION beware of recursion emacsclient function with program
function emacsclient ()
{
    ## default frame option
    option_frame=--reuse-frame

    while :; do

	case "$1" in

	    -nc|--no-client )
		shift
		## (... &) free up issueing cli
		(setsid /usr/bin/emacs "$@" &)
		return
		;;

	    -c|--create-frame )
		shift
		## create a new frame
		option_frame=--create-frame
		;;

	    -r|--reuse-frame )
		shift
		## already default frame option
		:
		;;

	    -t|--tty|-nw )
		shift
		#TODO run client as tty
		## prevent conflicting options
		option_frame=--tty
		;;

	    '' )
		## no (more) args
		break
		;;

	    * )
		## failsafe
		break
		;;

	esac

    done

    emacs_daemon

    ## main runmode
    ## usr/bin/emacsclient avoids recursion with function emacsclient
    /usr/bin/emacsclient --no-wait --alternate-editor='' "$option_frame" "$@"

    ## sway focus emacs container
    emacs_con_id=$(swaymsg --pretty --type get_tree \
	| grep "GNU Emacs at $HOST" \
	| awk '{print $1}' \
	| tr -d -c 0-9)

    [[ -n $emacs_con_id ]] && swaymsg "[con_id=${emacs_con_id}]" focus
}


## CAUTION beware of recursion emacsclient function and program
## this alias makes emacsclient completions available for em
alias em=emacsclient
## without client in separate process
alias emacs='emacs &'


alias lsblk='lsblk --ascii --tree -o name,uuid,fstype,path,size,fsuse%,fsused,label,mountpoint'
alias mountcols='mount | sort -k 1 | column -t'
# #alias cal='env TERM=xterm cal'
alias pwd='pwd && [[ $(command -v wl-copy) ]] && pwd | wl-copy -n'
alias rmln='unlink'
alias tree='tree -n --charset=unicode'
#alias tree='env TERM=xterm-256color tree'
#alias zsh="env ZDOTDIR="$XDG_CONFIG_HOME/zsh" zsh"
alias type='type -a'
alias watch='watch --differences --no-title --interval 1'

alias figlet="figlet -d $XDG_CONFIG_HOME/figlet"


## generate qr code
function qr ()
{
    ## usage: qr $(wl-paste)
    ##        echo hello | qr
    args="$@"
    [[ -z "$args" ]] && args="$(</dev/stdin)"
    ## qrcode inverse colors; using qrinv
    [[ $(command -v qrinv > /dev/null 2>&1) ]] \
	&& qrinv "$args" \
	    || qrencode --type utf8 "$args"
	    ## qrcode default colors; using qrencode
}


function wh ()
{
    printf '%s\n' 'which'
    which $1
    # echo
    printf '%s\n' 'whereis'
    whereis $1
    # echo
    printf '%s\n' 'whatis'
    whatis $1
}


## cli browsing
alias qb='qutebrowser'
alias sr="sr -browser=$BROWSERCLI"
alias surfraw="surfraw -browser=$BROWSER"


# file operations

## file listing
alias dir='dir --group-directories-first --color=auto'
alias fd='fd --color always'  ## flat view
alias ls="echo; ls --group-directories-first --color=auto"
alias lsfv='echo; fd --strip-cwd-prefix --list-details'  ## flat view with details
alias vdir='vdir --group-directories-first --color=auto'

## extracting information
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias rg='rg --hidden --sort path --smart-case'
# alias rg='rg --hidden --sort path --smart-case --line-number'

## file manipulation
alias cp='cp --archive --interactive --verbose'
alias mv='mv --interactive --verbose'
alias rm='trash'
alias mkdir='mkdir --parents --verbose'
alias mktemp="mktemp --tmpdir $DIR_TEMP"


## rsync for copy and move (better for large files)
function cpr ()
{
    rsync -aAXv --info=progress2,stats2 --partial --human-readable --modify-window=1 "$@"
}


function mvr ()
{
    rsync -aAXv --info=progress2,stats2 --partial --human-readable --modify-window=1 --remove-source-files "$@"
}


## eza for ls
#if command -v eza > /dev/null; then
#
#    alias ls="echo; $XDG_CONFIG_HOME/eza/eza_wrapper.sh"
#
#else
#
#    alias ls="echo; ls --color=auto"
#    #alias ls="echo; command ls $LS_OPTIONS"
#
#fi


# audio

## mpv
alias mpv='mpv --audio-display=no'

## pipewire
alias beep="pw-play $BEEP"
alias play='pw-play'

## pulseaudio
#alias beep="paplay $BEEP"


function say ()
{
    # usage: say $(sdate)
    #        sdate | say
    spch="$@"
    [[ -z $@ ]] && spch="$(</dev/stdin)"
    echo "$spch" | espeak
    # echo "$spch" | festival --tts
}


# date time epoch functions

## epoch decimal
alias now="date $TEPOCH"

## epoch hexadecimal
alias nowx="printf '%X\n' $(date $TEPOCH)"

function nown ()
{
    ## epoch nano decimal
    ## 1756211992.012016380

    ## #+ remove until first plus sign
    ## %0.9f 9 decimal floating point
    local tsen=$(date ${TEPOCH}.${TNANO#+})
    printf '%0.9f\n' "${tsen}"
}

function nownx ()
{
    ## epoch nano hexadecimal
    ## 68AC16C1.2ba33425

    ## #+ remove until first plus sign
    local tsen=$(date ${TEPOCH}.${TNANO#+})
    printf '%X.%x\n' "${tsen%.*}" "${tsen#*.}"
}

## dt prints datetime (default: decimal)
function dt ()
{
    ## date time decimal
    ## 20250825_100736

    local tse=$(date ${TEPOCH})
    date --date @${tse} +'%Y%m%d_%H%M%S'
}

function dte ()
{
    ## date time epoch decimal
    ## 20250825_100736_1756211992

    local tse=$(date ${TEPOCH})
    local tsd=$(date --date @${tse} +"$TDATE")
    local tst=$(date --date @${tse} +"$TTIME")
    printf '%d_%d_%d\n' "${tsd}" "${tst}" "${tse}"
}

function dtex ()
{
    ## date time epoch all hexadecimal
    ## 126B033C8C87_68AC1907

    local tse=$(date ${TEPOCH})
    local tsd=$(date --date @${tse} +"$TDATE")
    local tst=$(date --date @${tse} +"$TTIME")
    printf '%d_%d_%x\n' "${tsd}" "${tst}" "${tse}"
}

function dten ()
{
    ## date time epoch decimal
    ## 20250826_171150_1756221110.129674445

    local tsen=$(date ${TEPOCH}.${TNANO#+})
    local tse=$(date --date @${tsen} +"$TEPOCH")
    local tsd=$(date --date @${tsen} +"$TDATE")
    local tst=$(date --date @${tsen} +"$TTIME")
    local tsn=$(date --date @${tsen} +"$TNANO")
    printf '%d_%d_%d.%d\n' "${tsd}" "${tst}" "${tse}" "${tsn}"
}

function dtenx ()
{
    ## date time epoch hexadecimal
    ## 126B033C8C87_68AC1907.2ba33425

    local tsen=$(date ${TEPOCH}.${TNANO#+})
    local tse=$(date --date @${tsen} +"$TEPOCH")
    local tsd=$(date --date @${tsen} +"$TDATE")
    local tst=$(date --date @${tsen} +"$TTIME")
    local tsn=$(date --date @${tsen} +"$TNANO")
    printf '%X_%X_%X.%x\n' "${tsd}" "${tst}" "${tse}" "${tsn}"
}

## (for say)
alias sdate="echo date: $(date +'%A %d %B %Y')"
alias sweek="echo week: $(date +%V)"
alias stime="echo time: $(date +%R)"


# operating system

alias osid='c /etc/os-release && echo && hostnamectl'
alias fastfetch='fastfetch --logo small --logo-color-1 blue --logo-color-2 blue'


# network

#alias myip='dig myip.opendns.com @resolver1.opendns.com +dnssec +short'
alias myip='curl icanhazip.com'
alias exip='myip'
alias pubip='myip'
alias ping9='ping -D -i 1 -c 3 9.9.9.9'


# shell

alias ppid='ps -p $$ -o ppid='


# application configuration

## w3m -config is right, not --config as expected
alias calc=qalc
alias fim='fim --no-history'
alias w3m="w3m -config $XDG_CONFIG_HOME/w3m/config"
alias zathura='zathura --fork'
