#!/bin/sh
#
##
###                                      _ _
###  _____      ____ _ _   _    _____  _(_) |_
### / __\ \ /\ / / _` | | | |  / _ \ \/ / | __|
### \__ \\ V  V / (_| | |_| | |  __/>  <| | |_
### |___/ \_/\_/ \__,_|\__, |  \___/_/\_\_|\__|
###                    |___/
###
###  _ _|_ _ ._    _  _
### (_\/|_(_)|_)\/(_|(/_
###   /      |  /  _|
###
### sway exit
### rofi application that offers options to exit sway
### (c) 2019 cytopyge
###
##
#

exit=$(echo -e "cancel\nswaylock -F -c 000000\nsway exit\nsystemctl reboot\nsystemctl poweroff" | rofi \
	-dmenu \
	-monitor 0 \
	-location 1 \
	-width 100 \
	-lines 1 \
	-columns 5 \
	-separator-style none \
	-hide-scrollbar \
	-font "Source Code Pro 10" \
	-bw 0 \
	-i \
	-matching fuzzy \
	-cycle true \
	-disable-history \
	-color-normal "#000000, #999999, #000000, #005577, #ffffff" \
	-color-active "#222222, #b1b4b3, #222222, #007763, #b1b4b3" \
	-color-urgent "#222222, #b1b4b3, #222222, #77003d, #b1b4b3" \
	-color-window "#000000, #999999, #b1b4b3" \
	-kb-row-select "Tab" \
	-kb-row-tab "" \
	-p "E X I T ?   $(sway -v) " \
	)

[ -z $exit ] && exit

`echo $exit`

	# no comments inside settings
	# state: 'bg', 'fg', 'bgalt', 'hlbg', 'hlfg'
	# 'background', 'border', 'separator'
