#! /usr/bin/env sh

## get data
if [ -d /sys/class/power_supply/BAT0 ]; then

    batt_status="$(cat /sys/class/power_supply/BAT0/status | tr '[:upper:]' '[:lower:]')"

    batt_perc="$(cat /sys/class/power_supply/BAT0/capacity)"

#    ## translate from decimal to single hexadecimal digit
#    bt_pc_015=$(echo $(( batt_perc*16/100 )))
#    #bt_pc_015=$(echo $(( batt_perc*15/100 )))
#    batt_hex=$(echo "obase=16; ibase=10; $bt_pc_015" | bc)
#
#    # discharging - color background
#    # charging - color foregrtound
#    # E-F no color added
#    # A-D blue
#    # 8-9 yellow
#    # 5-7 magenta
#    # 0-4 red
#    hex_is_number=$(printf "$batt_hex" | grep -Eo '[0-9]')

    case $batt_status in

        discharging)
            flow="—"
            ;;

        charging)
            flow="+"
            ;;

        full | 'not charging')
            flow="="
            ;;

        *)
            flow="?"
            ;;

    esac

fi

## battery percentage
batt_perc_numeric=$(( batt_perc ))

## percentage conversion to hex
batt_afdec=$(echo "16-6/100*$batt_perc_numeric" | bc -l)
batt_afd=$(echo $batt_afdec | cut -d '.' -f 1)
batt_af=$(echo "obase=16; ibase=10; $batt_afd" | bc)

## full text
echo "${batt_af}$flow"

## short text
echo  ## none

## color
case $batt_status in

    discharging)
	## text
	(( $batt_perc < 19 )) && echo "#ffffb6"  ## yellow
	(( $batt_perc > 19 && $batt_perc <= 39 )) && echo "#000000"  ## black
	(( $batt_perc > 39 && $batt_perc <= 59 )) && echo "#000000"
	(( $batt_perc > 59 && $batt_perc <= 79 )) && echo "#000000"
	(( $batt_perc > 79 && $batt_perc <= 99 )) && echo "#777777"  ## grey77

	## background
	(( $batt_perc < 19 )) && echo "#ff6c60"  ## red
	(( $batt_perc > 19 && $batt_perc <= 39 )) && echo "#ffbf00"  ## amber
	(( $batt_perc > 39 && $batt_perc <= 59 )) && echo "#ffffb6"  ## yellow
	(( $batt_perc > 59 && $batt_perc <= 79 )) && echo "#999999"  ## grey99
	(( $batt_perc > 79 && $batt_perc <= 99 )) && echo "#000000"

	## border
	(( $batt_perc < 19 )) && echo "#ffffb6"
	(( $batt_perc > 19 && $batt_perc <= 39 )) && echo "#ffbf00"  ## amber
	(( $batt_perc > 39 && $batt_perc <= 59 )) && echo  ## none
	(( $batt_perc > 59 && $batt_perc <= 79 )) && echo  ## none
	(( $batt_perc > 79 && $batt_perc <= 99 )) && echo  ## none
	;;

    charging)
	## text
	(( $batt_perc < 19 )) && echo "#ff6c60"  ## red
	(( $batt_perc > 19 && $batt_perc <= 39 )) && echo "#ffbf00"  ## amber
	(( $batt_perc > 39 && $batt_perc <= 59 )) && echo "#ffffb6"  ## yellow
	(( $batt_perc > 59 && $batt_perc <= 79 )) && echo "#999999"  ## grey99
	(( $batt_perc > 79 && $batt_perc <= 99 )) && echo "#000000"

	## background
	(( $batt_perc < 19 )) && echo "#000000"  ## black
	(( $batt_perc > 19 && $batt_perc <= 39 )) && echo "#000000"  ## black
	(( $batt_perc > 39 && $batt_perc <= 59 )) && echo "#000000"
	(( $batt_perc > 59 && $batt_perc <= 79 )) && echo "#000000"
	(( $batt_perc > 79 && $batt_perc <= 99 )) && echo "#000000"

	## border
	(( $batt_perc < 19 )) && echo  ## none
	(( $batt_perc > 19 && $batt_perc <= 39 )) && echo  ## none
	(( $batt_perc > 39 && $batt_perc <= 59 )) && echo  ## none
	(( $batt_perc > 59 && $batt_perc <= 79 )) && echo  ## none
	(( $batt_perc > 79 && $batt_perc <= 99 )) && echo  ## none
	;;

    full | 'not charging')
	## text
	(( $batt_perc > 99 )) && echo "#777777"  ## grey77
	##background
	(( $batt_perc > 99 )) && echo "#000000"  ## black
	## border
	(( $batt_perc > 99 )) && echo  ## none
	;;

esac
