#!/bin/sh

if [[ -n $(ip route show) ]]; then

	i=$(ip route get 9.9.9.9 | awk '{print $5}')

	## internal mac

	case $i in

		tun0 | proton0)
			i_link=$(ip -oneline link | grep -v -i 'state down' | grep -v proton0)
			mac_full=$(echo "${i_link#*link/ether }" | awk '{print $1}')
			;;

		*)
			mac_full=$(cat /sys/class/net/$i/address | cut -c 13-)
			;;
	esac


	mac_in=$(echo $mac_full | tail --bytes 6)

	printf '%s\n' "$mac_in"

fi
