#! /usr/bin/env sh

mem_total=$(( $(grep -i -m 1 'memtotal' /proc/meminfo | awk '{print $2}' ) / 1000 ))
mem_avail=$(( $(grep -i -m 1 'memavail' /proc/meminfo | awk '{print $2}') / 1000 ))
mem_avail_perc=$(( 100 * mem_avail / mem_total ))

#mem_free=$(( $(grep -i -m 1 'memfree' /proc/meminfo | awk '{print $2}') / 1000 ))
#mem_free_perc=$(( 100 * mem_free / mem_total ))


## full text
printf "%05d" $mem_avail

## short text
echo  ## none

## color
## variable threshold value and interval
var=$(( 100 - mem_avail_perc ))  ## inverting the treshold
min=05
int=15

## text
(( $var > $(( min + 3 * int )) )) && echo "#ffffb6"  ## yellow
(( $var > $(( min + 2 * int )) && $var <= $(( min + 3 * int )) )) && echo "#000000"  ## black
(( $var > $(( min + 1 * int )) && $var <= $(( min + 2 * int )) )) && echo "#ffffb6"  ## yellow
(( $var > $(( min + 0 * int )) && $var <= $(( min + 1 * int )) )) && echo "#999999"  ## grey99
(( $var < $(( min + 0 * int )) )) && echo "#777777"  ## grey77

## background
(( $var > $(( min + 3 * int )) )) && echo "#ff6c60"  ## red
(( $var > $(( min + 2 * int )) && $var <= $(( min + 3 * int )) )) && echo "#ffffb6"  ## yellow
echo  ## none

## border
echo  ## none
