#! /usr/bin/env sh

#[TODO] posix compliance #!/bin/sh does not accept the array


i=$(ip -o -4 route show to default | awk '{print $5}')

# check for interface

if [ -z "$i" ]; then
	exit
fi


# rx 	received on interface (bytes)
# tx 	transmitted on interface (bytes)
# t	timestamp (nanoseconds (10^-9))

#rx0=$(cat /proc/net/dev | grep $i | awk '{print $2}')
tx0=$(cat /proc/net/dev | grep $i | awk '{print $10}')
t0=$(date +%s%N)

sleep 1

#rx1=$(cat /proc/net/dev | grep $i | awk '{print $2}')
tx1=$(cat /proc/net/dev | grep $i | awk '{print $10}')
t1=$(date +%s%N)


# drx	received on interface (kilobytes)
# dtx 	transmitted on interface (kilobytes)
# dt	elapsed time (seconds)

#drx=$((rx1-rx0))/1000
dtx=$((tx1-tx0))/1000
dt=$(((t1-t0)/1000000000))


# vrx	receive speed on interface (kbytes/s)
# vtx 	transmit speed on interface (kbytes/s)

#vrx=$(( drx / dt ))
vtx=$(( dtx / dt ))

## full text
printf "%4s\n" "$vtx"
#echo ${vtx}

## short text
echo  ## none

## color
## variable threshold value and interval
var=$vtx
min=200
int=200

## text
(( $var > $(( min + 3 * int )) )) && echo "#ffffb6"  ## yellow
(( $var > $(( min + 2 * int )) && $var <= $(( min + 3 * int )) )) && echo "#000000"  ## black
(( $var > $(( min + 1 * int )) && $var <= $(( min + 2 * int )) )) && echo "#ffffb6"  ## yellow
(( $var > $(( min + 0 * int )) && $var <= $(( min + 1 * int )) )) && echo "#999999"  ## grey99
(( $var < $(( min + 0 * int )) )) && echo "#777777"  ## grey77

## background
(( $var > $(( min + 3 * int )) )) && echo "#ff6c60"  ## red
(( $var > $(( min + 2 * int )) && $var <= $(( min + 3 * int )) )) && echo "#ffffb6"  ## yellow
echo  ## none

## border
echo  ## none
