#!/usr/bin/env sh

## focused container (window)
pid=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused == true) | .pid')

name=$(swaymsg -t get_tree | jq  ".. | select(.type?) | select(.pid == "$pid") | .name")

#workspace=$(swaymsg -t get_tree | jq  '.. | select(.nodes?) | select(.current_workspace) | .current_workspace' | sed 's/"//g')

type=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused == true) | .type')
[[ $type == '"floating_con"' ]] && con_type='[~]' || con_type='[]'

# NOTICE the eol is important for i3blocks
if [[ -n $pid ]]; then

    printf "%s  %s  %s  \n" "$name" $pid $con_type

fi
