#!/usr/bin/env sh

## focused container (window)
pid=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused == true) | .pid' | sed 's/null//')

name=$(swaymsg -t get_tree | jq  ".. | select(.type?) | select(.pid == "$pid") | .name" | sed 's/"//g')

#workspace=$(swaymsg -t get_tree | jq  '.. | select(.nodes?) | select(.current_workspace) | .current_workspace' | sed 's/"//g')

type=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused == true) | .type')
[[ $type == '"con"' ]] && con_type='[ ]' || con_type='[*]'

# NOTICE eol for i3blocks
if [[ -n $pid ]]; then

    printf '%s %6s %s\n' "$name" $pid "$con_type"

fi
