#!/usr/bin/env sh

cpu_temp=$(sensors | grep 'CPU' | awk '{print substr($0, 16, 2)}')
#cpu_temp=$(sensors | grep 'Tctl' | awk '{print substr($0, 16, 2)}')

#printf '%sC\n' "$cpu_temp"

echo ${cpu_temp}C
# echo text background border
# !! finer granularity than 2 stages causes unpredictable behaviour
[[ $cpu_temp -gt 80 ]] && exit 33
[[ $cpu_temp -gt 60 ]] && echo && echo "#ff73fd" #&& echo "#000000" #&& echo "#000000"

exit 0
