#!/usr/bin/env sh
volume=$(amixer -D pipewire sget Master | grep 'Left: ' | cut -d ' ' -f 5 | tr -d -c "[:digit:]")
#volume=$(amixer -D pulse sget Master | grep 'Left: ' | cut -d ' ' -f 7 | tr -d -c "[:digit:]")
#amixer -D pulse sget Master | grep 'Left: ' | awk -F '[][]' '{printf "%s",$2}'

mute=$(amixer get PCM | grep off)
#mute=$(amixer get Master | grep off)

if [[ -n $mute ]]; then

    status='X'

elif [[ -z $mute ]]; then

    status='<'

fi

printf '%s\n' "$volume""$status"
